<!-- The Error class and its subclasses -->

= Error classes =

<hr>
<pre>
NAME:                       "The classes 'Error', 'EvalError', 'RangeError', 'ReferenceError',
                             'SyntaxError', 'TypeError', and 'URIError'"
FILE:                       spec/library/Error.html
CATEGORY:                   Pre-defined classes
SOURCES:                    REFERENCE [1]
SPEC AUTHOR:                Lars
DRAFT STATUS:               DRAFT 1 - 2008-03-06
REVIEWED AGAINST ES3:       YES
REVIEWED AGAINST ERRATA:    YES
REVIEWED AGAINST BASE DOC:  YES
REVIEWED AGAINST PROPOSALS: YES
REVIEWED AGAINST CODE:      YES
REVIEWED AGAINST TICKETS:   YES
REVIEWS:                    (none)
IMPLEMENTATION STATUS:      ES4 RI
TEST CASE STATUS:           Unknown

CHANGES SINCE DRAFT 1 (2008-03-06)

  * Presentation:
    - improvements to status block above


NOTES

  * Due to a bug [2] in the reference implementation, the private
    methods in the error classes are currently in the namespace
    "Private", not in "private".  This will be changed eventually.

REFERENCES

[1] ECMAScript 3rd Edition Specification
[2] http:&#x2f;&#x2f;bugs.ecmascript.org/ticket/368

</pre>
<hr>

<P> ECMAScript provides a hierarchy of standard pre-defined error classes
rooted at the class ''Error'' (see <XREF target="class Error">).

<P> The ECMAScript implementation throws a new instance of one of
the pre-defined error classes when it detects certain run-time errors.  The
conditions under which run-time errors are detected are explained
throughout this Standard.  The description of each of the pre-defined error
classes contains a summary of the conditions under which an instance
of that particular error class is thrown.

<P> The class ''Error'' serves as the base class for all the classes
describing standard errors thrown by the ECMAScript implementation:
''EvalError'', ''RangeError'', ''ReferenceError'', ''SyntaxError'',
''TypeError'', and ''URIError''.
(See <XREF target="class EvalError">, <XREF target="class RangeError">,
<XREF target="class ReferenceError">, <XREF target="class SyntaxError">,
<XREF target="class TypeError">, <XREF target="class URIError">.)

<P> The class ''Error'' as well as all its pre-defined subclasses are
non-final and dynamic and may be subclassed by user-defined exception
classes.

<P> All the pre-defined subclasses of ''Error'' share the same structure.


<H1 id="class Error"> The class ''Error'' </h1>

<P> The class ''Error'' is a dynamic, non-final subclass of ''Object''.
Instances of ''Error'' are not thrown by the implementation; rather,
''Error'' is intended to serve as a base class for other error classes
whose instances represent specific classes of run-time errors.

== Synopsis ==

<P> The class ''Error'' provides the following interface:

{{{
dynamic class Error extends Object 
{
    <SIGNATURE file="Error.es" name="public function Error">
    <SIGNATURE file="Error.es" name="static meta function invoke">
    
    static public const length = 1
    
    <SIGNATURE file="Error.es" name="override intrinsic function toString">
    <SIGNATURE file="Error.es" name="override helper function getClassName">
}
}}}

<P> The ''Error'' prototype object provides these direct properties:

{{{
    toString: function () <LDOTS>
    name:     "Error"
    message:  <LDOTS>
}}}

== Methods on the ''Error'' class ==

=== new Error (message) ===

<DESC> When the ''Error'' constructor is called as part of a
''new&nbsp;Error'' expression it initialises the newly created object:
If //message// is not **undefined**, the dynamic ''message'' property
of the newly constructed ''Error'' object is set to ''string(//message//)''.

<SHORTIMPL>
<INCLUDE file="Error.es" name="public function Error">

=== Error (message) ===

<DESC> When the ''Error'' class object is called as a function, it
creates and initialises a new ''Error'' object by invoking the
''Error'' constructor.

<RETN> The ''Error'' class object called as a function returns a new
''Error'' object.

<SHORTIMPL>
<INCLUDE file="Error.es" name="static meta function invoke">


== Methods on ''Error'' instances ==

=== intrinsic::toString ( ) ===

<DESC> The intrinsic ''toString'' method converts the ''Error'' object
to an implementation-defined string.

<RETN> A ''string'' object.

<SHORTIMPL>
<INCLUDE file="Error.es" name="override intrinsic function toString">

<P> The private function ''toString'' is implementation-defined.

=== helper::getClassName ( ) ===

<DESC> The helper method ''getClassName'' overrides the method defined
in ''Object'' and makes the pre-defined subclasses of ''Error'' appear
to have the [[Class]] value ''"Error"''.

<NOTE> The helper method ''getClassName'' is a specification artifact.
The protocol it defines for overriding [[Class]] is not available to
user code.

<RETN> The helper method ''getClassName'' returns a string.

<SHORTIMPL>
<INCLUDE file="Error.es" name="override helper function getClassName">
{{{
helper function isExactlyType(obj, cls)
    let (objtype = reflect::typeOf(obj))
        cls.reflect::isSubtypeOf(objtype) && objtype.reflect::isSubtypeOf(cls);
}}}


== Methods on the ''Error'' prototype object ==

=== toString ( ) ===

<DESC> The prototype ''toString'' method calls the private ''toString'' method.

<RETN> The prototype ''toString'' method returns a ''string'' object.

<SHORTIMPL>
<INCLUDE file="Error.es" name="prototype function toString">

== Value properties on the ''Error'' prototype object ==

=== name ===

<P> The initial value of the ''name'' prototype property is the string
"''Error''".

=== message ===

<P> The initial value of the ''message'' prototype property is an
implementation-defined string.


<!----------------------------------------------------------------------->

<H1 id="class EvalError"> The class ''EvalError'' </H1>

<P> The implementation throws a new ''EvalError'' instance when it
detects that the global function ''eval'' was used in a way that is
incompatible with its definition.  See sections XXX.

<FIXME> Clean up the section references when we reach final draft.

== Synopsis ==

<P> The ''EvalError'' class provides this interface:

{{{
dynamic class EvalError extends Error
{
    <SIGNATURE file="EvalError.es" name="public function EvalError">
    <SIGNATURE file="EvalError.es" name="static meta function invoke">
    
    static public const length = 1
}
}}}

<P> The ''EvalError'' prototype object provides these direct properties:
{{{
    name:    "EvalError"
    message: <LDOTS>
}}}

== Methods on the ''EvalError'' class ==

=== new EvalError (message) ===

<DESC> When the ''EvalError'' constructor is called as part of a
''new&nbsp;EvalError'' expression it initialises the newly created
object by delegating to the ''Error'' constructor.

<SHORTIMPL>
<INCLUDE file="EvalError.es" name="public function EvalError">


=== EvalError (message) ===

<DESC> When the ''EvalError'' class object is called as a function, it
creates and initialises a new ''EvalError'' object by invoking the
''EvalError'' constructor.

<RETN> The ''EvalError'' class object called as a function returns a
new ''EvalError'' object.

<SHORTIMPL>
<INCLUDE file="EvalError.es" name="static meta function invoke">


== Value properties on the ''EvalError'' prototype object ==

=== name ===

<P> The initial value of the ''name'' prototype property is the string "''EvalError''".

=== message ===

<P> The initial value of the ''message'' prototype property is an implementation-defined string.


<!----------------------------------------------------------------------->

<H1 id="class RangeError"> The class ''RangeError'' </H1>

<P> The implementation throws a new ''RangeError'' instance when it
detects that a numeric value has exceeded the allowable range.  See
sections XXX.

<FIXME> Clean up the section references when we reach final draft.

== Synopsis ==

<P> The ''RangeError'' class provides this interface:

{{{
dynamic class RangeError extends Error
{
    <SIGNATURE file="RangeError.es" name="public function RangeError">
    <SIGNATURE file="RangeError.es" name="static meta function invoke">
    
    static public const length = 1
}
}}}

<P> The ''RangeError'' prototype object provides these direct properties:
{{{
    name:    "RangeError"
    message: <LDOTS>
}}}

== Methods on the ''RangeError'' class ==

=== new RangeError (message) ===

<DESC> When the ''RangeError'' constructor is called as part of a
''new&nbsp;RangeError'' expression it initialises the newly created
object by delegating to the ''Error'' constructor.

<SHORTIMPL>
<INCLUDE file="RangeError.es" name="public function RangeError">


=== RangeError (message) ===

<DESC> When the ''RangeError'' class object is called as a function, it
creates and initialises a new ''RangeError'' object by invoking the
''RangeError'' constructor.

<RETN> The ''RangeError'' class object called as a function returns a
new ''RangeError'' object.

<SHORTIMPL>
<INCLUDE file="RangeError.es" name="static meta function invoke">


== Value properties on the ''RangeError'' prototype object ==

=== name ===

<P> The initial value of the ''name'' prototype property is the string "''RangeError''".

=== message ===

<P> The initial value of the ''message'' prototype property is an implementation-defined string.


<!----------------------------------------------------------------------->

<H1 id="class ReferenceError"> The class ''ReferenceError'' </H1>

<P> The implementation throws a new ''ReferenceError'' instance when it
detects an invalid reference value. See sections XXX.

<FIXME> Clean up the section references when we reach final draft.

== Synopsis ==

{{{
dynamic class ReferenceError extends Error
{
    <SIGNATURE file="ReferenceError.es" name="public function ReferenceError">
    <SIGNATURE file="ReferenceError.es" name="static meta function invoke">
    
    static public const length = 1
}
}}}

<P> The ''ReferenceError'' prototype object provides these direct properties:
{{{
    name:    "ReferenceError"
    message: <LDOTS>
}}}

== Methods on the ''ReferenceError'' class ==

=== new ReferenceError (message) ===

<DESC> When the ''ReferenceError'' constructor is called as part of a
''new&nbsp;ReferenceError'' expression it initialises the newly created
object by delegating to the ''Error'' constructor.

<SHORTIMPL>
<INCLUDE file="ReferenceError.es" name="public function ReferenceError">


=== ReferenceError (message) ===

<DESC> When the ''ReferenceError'' class object is called as a function, it
creates and initialises a new ''ReferenceError'' object by invoking the
''ReferenceError'' constructor.

<RETN> The ''ReferenceError'' class object called as a function returns a
new ''ReferenceError'' object.

<SHORTIMPL>
<INCLUDE file="ReferenceError.es" name="static meta function invoke">


== Value properties on the ''ReferenceError'' prototype object ==

=== name ===

<P> The initial value of the ''name'' prototype property is the string "''ReferenceError''".

=== message ===

<P> The initial value of the ''message'' prototype property is an implementation-defined string.


<!----------------------------------------------------------------------->

<H1 id="class SyntaxError"> The class ''SyntaxError'' </H1>

<P> The implementation throws a new ''SyntaxError'' instance when a
parsing error has occurred. See sections XXX.

<FIXME> Clean up the section references when we reach final draft.

== Synopsis ==

{{{
dynamic class SyntaxError extends Error
{
    <SIGNATURE file="SyntaxError.es" name="public function SyntaxError">
    <SIGNATURE file="SyntaxError.es" name="static meta function invoke">
    
    static public const length = 1
}
}}}

<P> The ''SyntaxError'' prototype object provides these direct properties:
{{{
    name:    "SyntaxError"
    message: <LDOTS>
}}}

== Methods on the ''SyntaxError'' class ==

=== new SyntaxError (message) ===

<DESC> When the ''SyntaxError'' constructor is called as part of a
''new&nbsp;SyntaxError'' expression it initialises the newly created
object by delegating to the ''Error'' constructor.

<SHORTIMPL>
<INCLUDE file="SyntaxError.es" name="public function SyntaxError">


=== SyntaxError (message) ===

<DESC> When the ''SyntaxError'' class object is called as a function, it
creates and initialises a new ''SyntaxError'' object by invoking the
''SyntaxError'' constructor.

<RETN> The ''SyntaxError'' class object called as a function returns a
new ''SyntaxError'' object.

<SHORTIMPL>
<INCLUDE file="SyntaxError.es" name="static meta function invoke">


== Value properties on the ''SyntaxError'' prototype object ==

=== name ===

<P> The initial value of the ''name'' prototype property is the string "''SyntaxError''".

=== message ===

<P> The initial value of the ''message'' prototype property is an implementation-defined string.


<!----------------------------------------------------------------------->

<h1 id="class TypeError"> The class ''TypeError'' </H1>

<P> The implementation throws a new ''TypeError'' instance when it has
detected that the actual type of an operand is different than the
expected type. See sections XXX.

<FIXME> Clean up the section references when we reach final draft.

== Synopsis ==

{{{
dynamic class TypeError extends Error
{
    <SIGNATURE file="TypeError.es" name="public function TypeError">
    <SIGNATURE file="TypeError.es" name="static meta function invoke">
    
    static public const length = 1
}
}}}

<P> The ''TypeError'' prototype object provides these direct properties:
{{{
    name:    "TypeError"
    message: <LDOTS>
}}}

== Methods on the ''TypeError'' class ==

=== new TypeError (message) ===

<DESC> When the ''TypeError'' constructor is called as part of a
''new&nbsp;TypeError'' expression it initialises the newly created
object by delegating to the ''Error'' constructor.

<SHORTIMPL>
<INCLUDE file="TypeError.es" name="public function TypeError">


=== TypeError (message) ===

<DESC> When the ''TypeError'' class object is called as a function, it
creates and initialises a new ''TypeError'' object by invoking the
''TypeError'' constructor.

<RETN> The ''TypeError'' class object called as a function returns a
new ''TypeError'' object.

<SHORTIMPL>
<INCLUDE file="TypeError.es" name="static meta function invoke">


== Value properties on the ''TypeError'' prototype object ==

=== name ===

<P> The initial value of the ''name'' prototype property is the string "''TypeError''".

=== message ===

<P> The initial value of the ''message'' prototype property is an implementation-defined string.


<!----------------------------------------------------------------------->

<H1 id="class URIError"> The class ''URIError'' </H1>

<P> The implementation throws a new ''URIError'' when one of the global
URI handling functions was used in a way that is incompatible with its
definition. See sections XXX.

<FIXME> Clean up the section references when we reach final draft.

== Synopsis ==

{{{
dynamic class URIError extends Error
{
    <SIGNATURE file="URIError.es" name="public function URIError">
    <SIGNATURE file="URIError.es" name="static meta function invoke">
    
    static public const length = 1
}
}}}

<P> The ''URIError'' prototype object provides these direct properties:
{{{
    name:    "URIError"
    message: <LDOTS>
}}}

== Methods on the ''URIError'' class ==

=== new URIError (message) ===

<DESC> When the ''URIError'' constructor is called as part of a
''new&nbsp;URIError'' expression it initialises the newly created
object by delegating to the ''Error'' constructor.

<SHORTIMPL>
<INCLUDE file="URIError.es" name="public function URIError">


=== URIError (message) ===

<DESC> When the ''URIError'' class object is called as a function, it
creates and initialises a new ''URIError'' object by invoking the
''URIError'' constructor.

<RETN> The ''URIError'' class object called as a function returns a
new ''URIError'' object.

<SHORTIMPL>
<INCLUDE file="URIError.es" name="static meta function invoke">


== Value properties on the ''URIError'' prototype object ==

=== name ===

<P> The initial value of the ''name'' prototype property is the string "''URIError''".

=== message ===

<P> The initial value of the ''message'' prototype property is an implementation-defined string.

<!-- End of Error.html -->
