try { } finally { }
try { } catch (x) { } 
try { } catch (const x:int) { } finally { }